### ISSUE TITLE
cancelBubble not working

### ISSUE THREAD

**Issue by colesimmons** [lavrton/react-konva#155]
I have an onContentMouseDown event on the stage and an onClick handler on a rect. Neither `e.cancelBubble = true;` or `e.evt.cancelBubble = true;` in the onClick seem to stop the onContentMouseDown from firing. The same applies for an onMouseDown event on the stage.

I'm trying to have the onContentMouseDown event fire when drawing on empty space but not when clicking an existing rect. Am I doing something wrong?

**Comment by colesimmons** [comment]
Alright, so it's an issue with konva and not react-konva, but cancelBubble doesn't stop onContentMouseDown events. The best solution as far as I can tell is to create an invisible rect with the same width + height as the stage/layer and use mouseDown/mouseMove/mouseUp. That way, bubbling will be cancelled when called on the other shapes.

**Comment by lavrton** [comment]
@blueberryfan do not use `onContentWheel` for your case. Just use `onWheel` for the stage too.
All "content" events are our of usual event bubbling flow.

**Comment by blueberryfan** [comment]
@lavrton Thanks for the tip, Anton, I'll have a look at that. 

From memory, I chose the content event because I built a zoom feature similar to what you'd find in a geographical map tool where you use the mouse scroll to zoom in and out, and because I needed it to zoom when scrolling anywhere, not just when the mouse pointer is over a shape, I had to use the content event.

Cheers

**Comment by lavrton** [comment]
@blueberryfan the behavior of many events slightly changes recently. Almost all events now trigger on empty space too.
