### ISSUE TITLE
There doesn't have onDragOver, onDragEnter, onDragLeave in typescript

### ISSUE THREAD

**Issue by Vnam92** [lavrton/react-konva#160]
JSX: 
`<Text 
   onDragOver={e => console.log(e)}
/>` 
Produces the error:
> TS2339: Property 'onDragOver' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<{ children?: ReactNode; }> & Read...'.

Could you help with this problem?
thx

**Comment by lavrton** [comment]
@Vnam92  `onDragOver` - is it a custom event? By default `Konva` has no such event. So they are not defined in typescript.

Probably we should all in our typings all customs events. But I am not sure how.

**Comment by Vnam92** [comment]
Yes `onDragOver` it's my attempt to check this event like `onDragStart` etc, wich works in react-konva right now. I supposed that all of konva events react-konva supports by default. Like this drop events: 
https://konvajs.github.io/docs/drag_and_drop/Drop_Events.html

Сould you advise how to workaround `onDragOver` in react-konva? 
Do you plan to add such events?

**Comment by lavrton** [comment]
By default `Konva` supports only `dragstart`, `dragmove` and `dragend`.

From your demo:`drop`, `dragenter`, `dragleave` and `dragover` are custom events that implemented manually on top of default Konva events. Unfortunately, due to Konva architecture, I can't include these events into default behavior.
But you can always add them manually as in the demo.

These custom events are not defined in typescript definitions. I guess we need to fix it somehow.
