### ISSUE TITLE
How to create brush function with react-konva

### ISSUE THREAD

**Issue by CodeBag414** [lavrton/react-konva#180]

**Comment by OKNoah** [comment]
Do you mean a paint brush?

**Comment by CodeBag414** [comment]
No, I just want a pencil function.

**Comment by OKNoah** [comment]
@CodeBag414 Maybe you'd like a package like this? https://github.com/James-Oldfield/react-paint

**Comment by CodeBag414** [comment]
I need to use React-Konva since I've already implemented other features I wanted.

**Comment by OKNoah** [comment]
Look in the Konva docs: https://konvajs.github.io/docs/sandbox/Free_Drawing.html

**Comment by CodeBag414** [comment]
Yes I know. But I'm not sure where to beginPath and where to closePath. I think I need to use scenceFunc but I'm not sure. Do you have experience in implementing pencil function with React-Konva?

**Comment by CodeBag414** [comment]
@lavrton What component should I use - Path, Shape or Layer for this pencil function? @OKNoah

**Comment by lavrton** [comment]
I will provide two demos. For drawing with "pencil" there are two main approaches:

### Manual drawing

Demo: https://codesandbox.io/s/8zvl1v00zl

In this demo to draw the line, you have to access the native canvas element and then use it as a source for `Konva.Image`.

This way is not "react-way" but it is very powerful and flexible, as you can do everything you want with canvas.

### State drawing

Demo: https://codesandbox.io/s/v380jlvwrl

This demo is in "react-way" because lines are stored in the state and `render` function generate them from the state.

**Comment by AbdullahZaydi** [comment]
Can we Create a Clone Stamp tool using Konvajs
