### ISSUE TITLE
if there are some ways to use the  konva cache ? 

### ISSUE THREAD

**Issue by malygin** [lavrton/react-konva#20]
I have app with 200 complex  objects on one layer and it's really slow, in Konva docs i found  Node caching, can i use this approach with react components

**Comment by lavrton** [comment]
Use. You can use "ref" and "refs" to get access to `Konva.Node` instance. And then you need to find the right moment for shape caching and it really depend your specific case.
Demo: http://jsbin.com/qofiwo/4/edit?js,output

**Comment by malygin** [comment]
thank you!

**Comment by Zabedovskiy** [comment]
Hi! Very strange cache, @lavrton. When I changed count of texts to 1000, I saw 15 fps at Stats. Although I checked use cache, I saw the same 15 fps at Stats. Are you sure that cache work fine in react-konva realization? It's really important question for me, because I have large map 482250x120250 and I have about 4000 objects on map, when I try dragging or scale it I have about 10-20 fps. It's realy few. In the future at this map will be about 30000 object and I scared about performance that I will have. Can you recomend best way for it, or may be i must change 'react-konva' to simple konva library, because on this example with cache all works fine with  count 20000k of objects

https://jsfiddle.net/513c8s5d/2/

**Comment by hsluoyz** [comment]
@lavrton can you make a demo about cache usage on react-konva?

**Comment by lavrton** [comment]
@hsluoyz use `ref` (https://reactjs.org/docs/refs-and-the-dom.html) to get access to Konva node. Then call `node.cache()`.
