### ISSUE TITLE
measureText()

### ISSUE THREAD

**Issue by arbesfeld** [lavrton/react-konva#6]
I am trying to surround a `Konva.Text` with a `Konva.Rect`, which requires that I measure the text before drawing the rectangle. How would you recommend that I accomplish this? 

Currently it requires two passes with React to first render the Text and then render the Rectangle, since I can't access the underlying `Konva.Text` element before it is rendered.

**Comment by lavrton** [comment]
You can use `Konva.Label` for such case http://konvajs.github.io/docs/shapes/Label.html.
Or you can use `width()` and `height()` of `Konva.Text` instance:
```javascript
const rect = new Konva.Rect({
  x: text.x(),
  y: text.y(),
  width: text.width(),
  height: text.height(),
  fill: 'yellow'
});
```
http://jsbin.com/wivakif/edit?html,js,output

**Comment by blueberryfan** [comment]
What's the recommended way of doing this in React (react-konva) though, like the OP asked? Render, somehow obtain text measurements, then force a re-render?

Also see issue 130.

**Comment by lavrton** [comment]
@blueberryfan  Something like this:
```js
class MyText extends React.Component {
  componentDidMount() {
    // do your text calculations here
    const width = this.textNode.getTextWidth();
  }
  render() {
    return (
      <Text
        {...someProps}
        ref={node => {
          this.textNode = node;
        }}
      />
    );
  }
}

```

**Comment by blueberryfan** [comment]
Thanks for the prompt response, @lavrton. I only just started to use React and your react-konva extension, and I like it. Good work!

The main thing I was wondering about is whether, as mentioned by @arbesfeld, it's not possible to get the width and use it to position some other component in a single render.

In your last example, am I right in thinking that once the width is obtained, I'd need to trigger a second rendering in which I could then use the width?

In my case, I have a Text and I'm drawing a Line after it, but I need to know the width of the text so that I can calculate the y-value for the Line. Basically, the width of the text varies, and therefore the y-value for the Line needs to be calculated dynamically, based on the width of the Text.

I'm thinking that in componentDidMount() I could grab the width of the Text, call setState() to store the width, and upon re-render use the state to re-position the Line. This would always require two renderings though, but maybe there's no way around it?

**Comment by lavrton** [comment]
@blueberryfan I don't know any good ways around. As I know this is a very popular practice in React apps.

Probably you can precalculate width somehow in `componentWillMount` with native canvas access, but I don't think it will give real benefits.

**Comment by blueberryfan** [comment]
Ok, great. Thanks for your input. I'll have a play and post back if I find a way of not having to re-render.
Cheers!

**Comment by blueberryfan** [comment]
I ended up doing what I described above, ie a double render, which makes sense.

**Comment by SyntaxRules** [comment]
Update: The following commit exposed `measureText()`: https://github.com/konvajs/konva/commit/18cce13ea51e69374ec0db9b86d3fd9e40005d85

Now you can measure the text before creating the rect with `konvaLayer.getContext().measureText("some text").width`.

**Comment by damiangreen** [comment]
@SyntaxRules the result of `measureText` appears to be less than the width of `textRef.current.width()` for some reason. I seem to have to hack a work around by adding additional pixels
