### ISSUE TITLE
[question] is react-konva practical for creating user interfaces?

### ISSUE THREAD

**Issue by tconroy** [lavrton/react-konva#68]
Hey there!

I'm creating a mobile-focused project with React. I want the UI animations and touch gestures to be very performant, and as near to native-like as possible, so I'm looking at implementing some sort of canvas based renderer for the app.

I've boiled down to two choices, react-canvas and react-konva.

The benefit of react-canvas to me seems to be that it's more targeted towards creating interfaces, wheras konva seems less so. That being said, Konva is still actively maintained and developed, while Flipboard seems to have let react-canvas fall behind. 

So I wanted to ask, how practical is it to use react-konva for building complete app UI, comparable to react-canvas?

Thanks for any input. :)

**Comment by lavrton** [comment]
Hello. First of all, it really depends on your interface. What exactly do you want to draw? Will it have animations, what kind of animations etc?

But my first answers is no. DO NOT USE `react-konva` and DO NOT USE `react-canvas`.

`react-canvas` is designed for building simple but very performant interfaces (in Flipboard UI they have just images and some text in a long list of posts). The issue here is that the project is not maintained anymore.

`react-konva` is not designed for building UI (here I mean classic UI - text, icons, buttons, inputs, forms, etc). It is designed for drawing on canvas in "react-style" and it is very useful when you need pixel manipulations, exporting to image, filters.

So for complete app UI I recommend to use our old friends - HTML + CSS.

**Comment by tconroy** [comment]
Hi @lavrton,

Thanks for the reply. Ultimately I agree, good old HTML and CSS are much more suitable for building UI's. Unfortunately we're running into a similar issue that Flipboard ran into, where mobile web performance just isn't there for the kind of almost-native-app-like experience we want to create with heavy animations, dynamic content, etc.

I suppose this could boil down to refining and optimizing our react render stack, but the idea of a canvas lib for building interfaces sounds like it combines the best of both worlds ( performance and precision of canvas, flexibility of the DOM ). But I suppose canvas libs just aren't there yet ( not to mention the various other trade offs, difficulty with text / links etc ).

Thanks for your honesty and candidness!

**Comment by lavrton** [comment]
As I mentioned before, I do not recommend to use `react-konva` for such purpose. Because I think it will be NOT faster than classic HTML. But I didn't make real tests, it is just my assumption. You can create small prototype and test by yourself, probably it will be good.
Another possible good solution is to create "canvas-ui-ultra-fast-library" by yourself manually (probably webgl performance will help here a lot, take a look into http://www.pixijs.com/). And then build react bridge on top of it (like `react-konva` is a bridge for Konva).
