### ISSUE TITLE
componentWillUnmount

### ISSUE THREAD

**Issue by moreCodeMoreFun** [lavrton/react-konva#70]
Hi,

This line to say thank you for the great job with react-konva.

However i'm encoutering this warning:

> Warning: There is an internal error in the React performance measurement code. Did not expect componentWillUnmount timer to start while componentWillUnmount timer is still in progress for another instance.

I spent some time to find the trigger, and there it is:

```
class Child extends Component {
  componentWillUnmount() {
  }

  render() {
    return (
      <Group />
    );
  }
}

class Parent extends Component {
  render() {
    return (
      <Stage>
        <Layer>
          <Child />
        </Layer>
      </Stage>
    );
  }
}
```

When there is no componentWillUnmount method in Child, nothing happen. But when this method exists, React notices the warning above.

I tried to find more information on it, but i didn't find similiar issues, so here i am.

Might you help me to know what i'm doing wrong?

**Comment by lavrton** [comment]
You are doing all right. I have this warning too. And as for now, I don't know how to fix it.
As it is just warning I don't care a lot about it. Also very soon I will have to rewrite `react-konva`, because `React` will change its internals a lot with Fiber (https://gist.github.com/duivvv/2ba00d413b8ff7bc1fa5a2e51c61ba43)

**Comment by moreCodeMoreFun** [comment]
Thank you for your quick reply.

Good luck for your rewrite.
