### ISSUE TITLE
React internal error when unmounting Stage

### ISSUE THREAD

**Issue by naorye** [lavrton/react-konva#86]
I have a login page with only login button (non-canvas page) and another page that contains Stage component with logout button.
When I press logout, the browser navigates to the login page. As a consequence Stage's componentWillUnmount is called and cause the following exception:
```
"Warning: There is an internal error in the React performance measurement code. Did not expect componentWillUnmount timer to start while componentWillUnmount timer is still in progress for another instance."
```

**Comment by naorye** [comment]
Anyone?

**Comment by lavrton** [comment]
@naorye this is just warning and I am just ignoring it.
I want to fix this issue later when I will have to rewrite react-konva because new React Fiber will be published.

**Comment by tommyschmiedel** [comment]
@naorye @lavrton I just came across the same warning. Ignoring it was not an option for me, because the component just wouldn't render under certain circumstances. I figured out that the warning only appeared when using class components, so refactoring to functional components may be a workaround for you at this point.
